[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "pandahub/__init__.py"

[project]
name = "pandahub"
description = "Data hub for pandapower and pandapipes networks based on MongoDB"
authors = [
    { name = "Jan Ulffers", email = "jan.ulffers@iee.fraunhofer.de" },
    { name = "Leon Thurner", email = "leon.thurner@retoflow.de" },
    { name = "Jannis Kupka", email = "jannis.kupka@retoflow.de" },
    { name = "Mike Vogt", email = "mike.vogt@iee.fraunhofer.de" },
    { name = "Joschka Thurner", email = "joschka.thurner@retoflow.de" },
    { name = "Alexander Scheidler", email = "alexander.scheidler@iee.fraunhofer.de" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    # Add the specific Python versions supported here, e.g.:
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
keywords = ["network", "analysis", "optimization", "automation", "grid", "energy", "engineering", "simulation"]
requires-python = ">=3.10"
dependencies = [
    "pandapower>=3.0",
    "pandapipes>=0.7.0",
    "pymongo",
    "pydantic",
    "pydantic-settings",
    "pymongoarrow",
    "blosc",
]
dynamic = ["version"]

[project.optional-dependencies]
rest-api = ["fastapi[standard-no-fastapi-cloud-cli]>=0.104.0", "fastapi-users[beanie]>=12.0"]

[project.urls]
Homepage = "https://github.com/e2nIEE/pandahub"
Documentation = "https://pandapipes.readthedocs.io"
Source = "https://github.com/e2nIEE/pandahub"
Repository = "https://github.com/e2nIEE/pandahub.git"
Issues = "https://github.com/e2nIEE/pandahub/issues"
Download = "https://pypi.org/project/pandahub/#files"
Changelog = "https://github.com/e2nIEE/pandahub/blob/develop/CHANGELOG.md"

[dependency-groups]
dev = [
    "ruff~=0.16.0",
    "pytest",
    "pytest-xdist",
    "simbench",
    "line_profiler",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
pydocstyle.convention = "numpy"
select = ["F",
    "E",
    "I",
    "N",
    "D",
    "UP",
    "ANN",
    "ASYNC",
    "S",
    "FBT",
    "B",
    "A",
    "C4",
    "DTZ",
    "T10",
    "EM",
    "ISC",
    "ICN",
    "LOG",
    "G",
    "PIE",
    "RSE",
    "PT",
    "RET",
    "SIM",
    "TID251",
    "TID252",
    "TCH",
    "ARG",
    "FLY",
    "NPY",
    "TD",
    "PD",
    "PERF",
    "INP001",
    "PL",
    "RUF",
]

ignore = [
    # line length (leave to formatter)
    "E501",
    # "too many" rules (branches, arguments, statements)
    "PLR0912",
    "PLR0913",
    "PLR0915",
    # do not require public module definitions
    "D100",
    # not compatible with formatter
    "ISC001",
    # No author in todos necessary
    "TD002",
    # No issue link in todos necessary
    "TD003",
    # ignore magic numbers rule (use named constants where appropriate manually)
    "PLR2004",
    # TODO: make boolean positional arguments keyword-only (breaking change)
    "FBT001",
]
